#!/bin/bash

trap FinalCleaning EXIT

test -z ${DOMAIN} && DOMAIN="TEST.LOCAL"
test -z ${APP_NAME} && APP_NAME='mufettis'

STR_SUCCESS="Success"
STR_ERROR="ERROR"

VAR_DIR="/usr/local/${APP_NAME}"
COMP_DIR="${VAR_DIR}/components"
CACHE_DIR="/var/cache/${APP_NAME}"
SSH_KEY="/var/lib/${APP_NAME}/ssh-key/${APP_NAME}"
PSSCRIPTS="${VAR_DIR}/psscripts"

MACHINE_LIST="${VAR_DIR}/machine-list"
MACHINE_NUMBER="$(wc -l < "${MACHINE_LIST}")"

ACTIVE_LIST="/tmp/${APP_NAME}.active"
PROCESS_ID_LIST="/tmp/${APP_NAME}.ids"
PREFIX_TEMP_DIR="${APP_NAME}"
TIMEOUT_VALUE=5
COMMON_SSH_OPTIONS="-o BatchMode=yes -o StrictHostKeyChecking=no -o ConnectTimeout=${TIMEOUT_VALUE}"

SYSDATE="$(date +%F)"
SYSDAY="$(date +%A)"
SYSHOUR="$(date +%H:%M)"
RDATE="${SYSDATE} - ${SYSDAY} ${SYSHOUR}"
LINKHEAD="reports/windowsreports"
LINK_OPT='target="_blank" rel="noopener noreferrer"'
WIN_PS_DIR="C:\\\\Windows\\\\Temp\\\\${APP_NAME}\\\\psscripts"
WEB_REPORT_DIR="/var/lib/${APP_NAME}/reports"


source ${COMP_DIR}/*

function CPUUsage()
{
	cat <(grep 'cpu ' /proc/stat) <(sleep 1 && grep 'cpu ' /proc/stat) | awk -v RS="" '{printf "%.0f\n", ($13-$2+$15-$4)*100/($13-$2+$15-$4+$16-$5)}'
}

function MemoryInfo()
{
	case ${1,,} in
		tenpercentofyourmemory)
			awk '/MemTotal/ {print int($2*0.1)}' /proc/meminfo;;
		available)
			awk '/MemAvailable/ {print $2}' /proc/meminfo;;
	esac
}

function WaitIfSystemResourceIsInsufficient()
{
	while true
	do
		if [ $(MemoryInfo Available) -gt $(MemoryInfo TenPercentOfYourMemory) -a $(CPUUsage) -lt 90 ]
		then
			break
		else
			sleep 5
		fi
	done
}

function ColorEcho()
{
	RED='\e[31m'
	GREEN='\e[32m'
	BLUE='\e[34m'
	YELLOW='\e[1;33m'
	L_BLUE='\e[1;34m'
	NONCOLOR='\e[0m'
	echo -e "${!1}${2}${NONCOLOR}"
}

function CreateNTLMAccessFile()
{
cat > ${1} << EOF
[windows:vars]
ansible_user=${2}
ansible_password=${3}
ansible_port=5985
ansible_connection=winrm
ansible_winrm_transport=ntlm

[windows]
${4}
EOF
}

function RunCommandViaWinRM()
{
	# 1 IP
	# 2 ACCESS FILE
	# 3 COMMAND
	test -z ${1} && return 2
	test -z ${2} && return 2
	test -z ${3} && return 2
	ansible "${1}" -T ${TIMEOUT_VALUE} -m win_command -a "powershell -ExecutionPolicy Unrestricted -Command \"${3}\"" -i ${2}
}

function RunCommandViaSSH()
{
	# 1 IP
	# 2 COMMAND
	# 3 PORT
	# 4 SSH OPTIONS
	# 5 USER
	# 6 PASSWORD
	test -z ${1} && return 2
	test -z ${2} && return 2
	test -z ${3} && local SSH_PORT=22 || local SSH_PORT="${3}"
	test -z ${5} && local USER=root || local USER="${5}"
	test -z ${6} || local SSHPASS="sshpass -p ${6}"
	${SSHPASS} ssh -p ${SSH_PORT} -i "${SSH_KEY}" ${COMMON_SSH_OPTIONS} ${4} ${USER}@${1} -- "${2}"
}

function RunLocalScriptRemotelyViaSSH()
{
	# 1 IP
	# 2 SCRIPT
	# 3 PORT
	# 4 SSH OPTIONS
	# 5 USER
	# 6 PASSWORD
	test -z ${1} && return 2
	test -z ${2} && return 2
	test -z ${3} && local SSH_PORT=22 || local SSH_PORT="${3}"
	test -z ${5} && local USER=root || local USER="${5}"
	test -z ${6} || local SSHPASS="sshpass -p ${6}"
	${SSHPASS} ssh -p ${SSH_PORT} -i "${SSH_KEY}" ${COMMON_SSH_OPTIONS} ${4} ${USER}@${1} -- sh -s < ${2}
}

function CopyFilesViaWinRM()
{
	# 1 IP
	# 2 ACCESS FILE
	# 3 SOURCE
	# 4 DESTINATION
	test -z ${1} && return 2
	test -z ${2} && return 2
	test -z ${3} && return 2
	test -z ${4} && return 2
	ansible "${1}" -T ${TIMEOUT_VALUE} -m win_copy -a "src=${3} dest=${4}" -i ${2}
}

function CopyFilesViaSSH()
{
	# 1 IP
	# 2 SOURCE
	# 3 DESTINATION
	# 4 PORT
	# 5 SSH OPTIONS
	# 6 USER
	# 7 PASSWORD
	test -z ${1} && return 2
	test -z ${2} && return 2
	test -z ${3} && return 2
	test -z ${4} && local SSH_PORT=22 || local SSH_PORT="${4}"
	test -z ${6} && local USER=root || local USER="${6}"
	test -z ${7} || local SSHPASS="sshpass -p ${7}"
	${SSHPASS} scp -P ${SSH_PORT} -i "${SSH_KEY}" ${COMMON_SSH_OPTIONS} ${5} ${USER}@${1} "${2}" "${3}"
}

function AddToList()
{
	grep -q "^${1}$" "${2}" 2>/dev/null || echo "${1}" >> ${2}
}

function CreateTempDir()
{
	TEMP_DIR=$(mktemp -d "/tmp/${PREFIX_TEMP_DIR}.XXXXXXX")
}

function CheckLivesViaPing()
{
	# 1 IP
	ping "${1}" -w ${TIMEOUT_VALUE} -c 1 2>&1 > /dev/null

}

function CheckLivesViaWinRM()
{
	# 1 IP
	# 2 ACCESS FILE
	test -z ${1} && return 2
	test -z ${2} && return 2
	ansible "${1}" -T ${TIMEOUT_VALUE} -m win_shell -a "whoami;hostname;(Get-WmiObject win32_operatingsystem).caption;(Get-WmiObject -Class Win32_ComputerSystem).Domain;(Get-ItemProperty HKLM:\SOFTWARE\Microsoft\PowerShell\3\PowerShellEngine).PowerShellVersion" -i "${2}"
}

function CheckLivesViaSSH()
{
	# 1 IP
	# 2 PORT
	# 3 SSH OPTIONS
	# 4 USER
	# 5 PASSWORD
	test -z ${1} && return 2
	test -z ${2} && local SSH_PORT=22 || local SSH_PORT="${2}"
	test -z ${4} && local USER=root || local USER="${4}"
	test -z ${5} || local SSHPASS="sshpass -p ${5}"
	${SSHPASS} ssh -p ${SSH_PORT} -i "${SSH_KEY}" ${COMMON_SSH_OPTIONS} ${3} ${USER}@${1} -- 'whoami;cat /etc/issue.net;hostname;uname -a'
}

function AddHostsFile()
{
	# 1 IP
	# 2 DNS
	printf "${1}\t${2}\n" >> /etc/hosts
}

function CheckInsideHostsFile()
{
	# 1 IP
	# 2 DNS
	test -z ${1} && return 2
	test -z ${2} && return 2
	grep -qE "^${1}|${2}$" /etc/hosts
}

function FinalCleaning()
{
	rm -rf "${PROCESS_ID_LIST}" "/tmp/${PREFIX_TEMP_DIR}.*"
}

function KeepProcessID()
{
	# 1 UNIQUE
	# 2 PROCESS ID
	test -z ${1} && return 2
	test -z ${2} && return 2
	printf "${1},${2}\n" >> "${PROCESS_ID_LIST}"
}

function DeleteProcessID()
{
	# 1 UNIQUE
	test -z ${1} && return 2
	test -f "${PROCESS_ID_LIST}" || return 1
	sed -i "/^\$/,/${1}/d" "${PROCESS_ID_LIST}"
}

function FetchFromMachineList()
{
	# 1 MACHINE LIST LINE NUMBER
	test -z ${1} && return 2
	sed -n ${1}p "${MACHINE_LIST}"
}

function ObtainingMachineInformation()
{
	UNIQUE="$(sha256sum <<< ${1} | awk '{print $1}')"
	IP="$(awk -F "," '{print $1}' <<< ${1})"
	HNAME="$(awk -F "," '{print $2}' <<< ${1})"
	MACHINE_TYPE="$(awk -F "," '{print $3}' <<< ${1})"
	PORT="$(awk -F "," '{print $4}' <<< ${1})"
	SSH_OPTIONS="$(awk -F "," '{print $5}' <<< ${1})"
	USER="$(awk -F "," '{print $6}' <<< ${1})"
	PASSWORD="$(awk -F "," '{print $7}' <<< ${1} | base64 -d)"
}

function Preliminary()
{
	MACHINE_WORK_DIR="${CACHE_DIR}/${UNIQUE}"
	OUTPUTS_DIR="${MACHINE_WORK_DIR}/outputs"
	HTML_DIR="${MACHINE_WORK_DIR}/html"
	WEB_HTML_DIR="${WEB_REPORT_DIR}/${MACHINE_TYPE,,}reports/${HNAME}"

	# Liveness and connectivity checks
	CheckLivesViaPing ${IP} || return 1
	
	mkdir -p "${MACHINE_WORK_DIR}"
	mkdir -p "${OUTPUTS_DIR}"
	mkdir -p "${HTML_DIR}"
	mkdir -p "${WEB_HTML_DIR}"

	case "${MACHINE_TYPE,,}" in
		windows)
			ACCESS="${MACHINE_WORK_DIR}/access-file"
			CreateNTLMAccessFile "${ACCESS}" "${USER}" "${PASSWORD}" "${IP}"
			echo "${IP}" > "${MACHINE_WORK_DIR}/output"
			CheckLivesViaWinRM "${IP}" "${ACCESS}" > "${MACHINE_WORK_DIR}/output" 2>&1
			;;
		linux|vmware)
			echo "${IP}" > "${MACHINE_WORK_DIR}/output"
			CheckLivesViaSSH "${IP}" "${PORT}" "${SSH_OPTIONS}" "${USER}" "${PASSWORD}" > "${MACHINE_WORK_DIR}/output" 2>&1
			;;
		*)
			return 1
	esac

	local EXIT_CODE=${?}

	if [ ${EXIT_CODE} == 0 ]
	then
		test -f "${MACHINE_WORK_DIR}/output" && mv "${MACHINE_WORK_DIR}/output" "${MACHINE_WORK_DIR}/machine-info"
		AddToList "${UNIQUE}" "${ACTIVE_LIST}"
		test -z ${HNAME} && HNAME="$(sed -n "3p" "${MACHINE_WORK_DIR}/machine-info")"
		test ! -z ${QUERY} && ColorEcho "GREEN" "${IP}\t${STR_SUCCESS}"
	else
		test -f "${MACHINE_WORK_DIR}/output" && mv "${MACHINE_WORK_DIR}/output" "${MACHINE_WORK_DIR}/machine-error"
		test ! -z ${QUERY} && ColorEcho "RED" "${IP}\t${STR_ERROR}"
	fi
	
	test ! -z ${QUERY} && DeleteProcessID "${UNIQUE}"

	return ${EXIT_CODE}
}

function StartAudit()
{
	case "${MACHINE_TYPE,,}" in
		windows)
			StartWindowsAudit
			;;
		linux)
			StartLinuxAudit
			;;
		vmware)
			StartVMWareAudit
			;;
	esac
	
	DeleteProcessID "${UNIQUE}"
}

function StartWindowsAudit()
{
	# We trigger the commands to run on the machine from this function.
	# ${UNIQUE}
	# ${IP}
	# ${HNAME}
	# ${MACHINE_TYPE}
	# ${PORT}
	# ${SSH_OPTIONS}
	# ${USER}
	# ${PASSWORD}
	# ${MACHINE_WORK_DIR}
	
	source "${VAR_DIR}/windowsaudit"
}

function StartLinuxAudit()
{
	# We trigger the commands to run on the machine from this function.
	# ${UNIQUE}
	# ${IP}
	# ${HNAME}
	# ${MACHINE_TYPE}
	# ${PORT}
	# ${SSH_OPTIONS}
	# ${USER}
	# ${PASSWORD}
	# ${MACHINE_WORK_DIR}

	source "${VAR_DIR}/linuxaudit"
}

function StartVMWareAudit()
{
	# We trigger the commands to run on the machine from this function.
	# ${UNIQUE}
	# ${IP}
	# ${HNAME}
	# ${MACHINE_TYPE}
	# ${PORT}
	# ${SSH_OPTIONS}
	# ${USER}
	# ${PASSWORD}
	# ${MACHINE_WORK_DIR}

	RunLocalScriptRemotelyViaSSH "${IP}" "${VAR_DIR}/vmware-createreport" "${PORT}" "${SSH_OPTIONS}" "${USER}" "${PASSWORD}"
	CopyFilesViaSSH "${IP}" "/tmp/*-report.tar.gz" "${MACHINE_WORK_DIR}" "${PORT}" "${SSH_OPTIONS}" "${USER}" "${PASSWORD}"
	test -f "${MACHINE_WORK_DIR}/*-report.tar.gz" && tar -xzf "${MACHINE_WORK_DIR}/*-report.tar.gz" -C "${OUTPUTS_DIR}"
}

function WaitForProcessesToFinish()
{
	while true
	do
		test ! -s "${PROCESS_ID_LIST}" && break
		sleep 1
	done
}

function MainProcess()
{
	rm -rf "${CACHE_DIR}" "${ACTIVE_LIST}"
	mkdir -p "${CACHE_DIR}"
	T=1

	if [ "${1,,}" == "query" ]
	then
		QUERY=true
		while [ ${T} -le ${MACHINE_NUMBER} ]
		do
			WaitIfSystemResourceIsInsufficient
			local MACHINE_INFO=$(FetchFromMachineList "${T}")
			T=$((T+1))
			ObtainingMachineInformation "${MACHINE_INFO}"
			Preliminary &
			KeepProcessID "${UNIQUE}" "${!}"
	        done
	else
		while [ ${T} -le ${MACHINE_NUMBER} ]
		do
			WaitIfSystemResourceIsInsufficient
			local MACHINE_INFO=$(FetchFromMachineList "${T}")
			T=$((T+1))
			ObtainingMachineInformation "${MACHINE_INFO}"
			Preliminary || continue
			StartAudit &
			KeepProcessID "${UNIQUE}" "${!}"
	        done
	fi
	WaitForProcessesToFinish
}

MainProcess $@
